# Generated by Django 4.1 on 2022-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('height', models.FloatField()),
                ('age', models.IntegerField()),
                ('club', models.CharField(max_length=90)),
                ('skillfull_leg', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
