# Generated by Django 4.1 on 2022-08-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantel',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
    ]
