# Generated by Django 4.0.6 on 2022-09-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantel', '0002_alter_plantel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plantel/'),
        ),
    ]
