# Generated by Django 4.1 on 2022-08-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
    ]
