# Generated by Django 4.0.6 on 2022-09-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadios',
            options={'verbose_name': 'Estadio', 'verbose_name_plural': 'Estadios'},
        ),
    ]
