# Generated by Django 4.0.6 on 2022-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('team1', models.CharField(max_length=40)),
                ('team2', models.CharField(max_length=40)),
                ('team3', models.CharField(max_length=40)),
                ('team4', models.CharField(max_length=40)),
            ],
        ),
    ]
