# Generated by Django 4.0.6 on 2022-08-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
